version: "3.9"
services:
  app:
    container_name: rabbit_app
    env_file:
      - .env
    build: ./app
    command: python main.py
    restart: on-failure
    depends_on:
      - rabbitmq
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana_storage:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning/
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - prometheus
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    restart: always
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - ./prometheus:/prometheus
      - alertmanager_data:/data
    command:
      - "--config.file=/prometheus/alertmanager.yml"
      - "--storage.path=/data"
    ports:
      - 9093:9093
    depends_on:
      - prometheus
    restart: always
  rabbitmq:
    image: rabbitmq:3-management
    container_name: ${RABBITMQ_HOST}
    env_file:
      - .env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    restart: always
  rabbitmq-exporter:
    image: kbudde/rabbitmq-exporter
    container_name: rabbitmq-exporter
    environment:
      RABBIT_URL: "http://${RABBITMQ_HOST}:${RABBITMQ_MANAGEMENT_PORT}"
      RABBIT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBIT_PASSWORD: "${RABBITMQ_DEFAULT_PASS}"
      PUBLISH_PORT: 9419
      SKIPVERIFY: true
    ports:
      - 9419:9419
    depends_on:
      - rabbitmq
    restart: always
  mailserver:
    image: rnwood/smtp4dev
    container_name: mailserver
    ports:
      - 25:25
      - 9000:80
    restart: always
volumes:
  grafana_storage:
  rabbitmq_data:
  alertmanager_data:
  prometheus_data:
