global:
  smtp_smarthost: "mailserver:25"
  smtp_from: "prometheus@localhost.com"
  smtp_require_tls: false

route:
  receiver: "email"
  group_by: ["alertname"]
  group_wait: 5s
  group_interval: 5s
  repeat_interval: 30s
  routes:
    - matchers:
        - alertname = "RabbitMQConnectionsHigh"
      receiver: "email"
    - matchers:
        - alertname = "RabbitMQServiceDown"
      receiver: "email"

receivers:
  - name: "email"
    email_configs:
      - to: "admin@localhost.com"
