groups:
  - name: rabbitmq-alerts
    rules:
      - alert: RabbitMQConnectionsHigh
        expr: rabbitmq_connections > 5
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High RabbitMQ Connections"
          description: "RabbitMQ connections are greater than 5 for more than 1 minute."
      - alert: RabbitMQServiceDown
        expr: rabbitmq_up == 0
        for: 20s
        labels:
          severity: critical
        annotations:
          summary: "RabbitMQ Service Down"
          description: "RabbitMQ service is not responding for more than 20 seconds."
