global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - "alert-rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: rabbitmq-exporter
    static_configs:
      - targets: ["rabbitmq-exporter:9419"]
